INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('102326','Dr Sasikumar M','sasi@cdac.in', '31-Jul','Male', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210101','Mr Abhishek Kumar Gangwar','abhishekg@cdac.in', '01-Apr','Male', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210118','Mr Alex Mathew','alexm@cdac.in', '30-May','Male', 'CANTEEN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210201','Mr Amol Suroshe','amol@cdac.in', '23-Mar','Male', 'ITSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210303','Mr Mohasin Sutar','mohasin@cdac.in', '02-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210411','Mr Ashok Mukund Naik','amnaik@cdac.in', '12-Mar','Male', 'CANTEEN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210503','Mr Balaji Kodandapani Sorakapet','skbalaji@cdac.in', '17-Jun','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210701','Ms Archana Rane','archana@cdac.in', '26-Sep','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210721','Mr N K Birje','nkbirje@cdac.in', '28-Nov','Male', 'CANTEEN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210912','Ms Gracy Abreo','gracy@cdac.in', '17-Nov','Female', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210922','Ms Anuradha Subramanian','anuradha@cdac.in', '27-Nov','Female', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('211012','Ms Madhavi Salvi','smadhavi@cdac.in', '11-Jul','Female', 'HRD');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('211326','Ms Bageerathi Krishnan Iyer','sudhab@cdac.in', '01-Aug','Female', 'COURSE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('211415','Ms Truptee C Shah','trupti@cdac.in', '01-Jan','Female', 'Library');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('211426','Mr J D Hande','jdhande@cdac.in', '20-Mar','Male', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('211517','Ms Renuka Chavan','raihna@cdac.in', '04-Feb','Female', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('211717','Ms Sabrina Pereira','sabrina@cdac.in', '08-Feb','Female', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('212001','Mr Atul T Dhengre','atul@cdac.in', '01-Mar','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('212801','Dr C P Johnson','johnson@cdac.in', '03-May','Male', 'EDU TRN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('212901','Ms Cini Radhakrishnan','cini@cdac.in', '22-Jul','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('213001','Mr Chandra Shekhar','shekhar@cdac.in', '27-Apr','Male', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('214401','Mr Golden Raymond Bhengra','raymond@cdac.in', '12-Jan','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('215401','Mr Jeetendra Jagtap','jeetendraj@cdac.in', '23-Aug','Male', 'CNIE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('215801','Mr Kapil Kant Kamal','kapil@cdac.in', '12-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('216301','Ms Leena Chourey','leenac@cdac.in', '03-May','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('217101','Mr Manish Kumar','kmanish@cdac.in', '04-Jan','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('217501','Ms Manju Kurup','menon@cdac.in', '19-Dec','Female', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('217801','Mr Nipun Pandey','nipun@cdac.in', '31-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('217901','Ms Nirmala Salam','nirmala@cdac.in', '08-Nov','Female', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('218001','Mr Navnath Kadam','navnath@cdac.in', '07-Jan','Male', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('218801','Mr Pranaw Kumar','pranaw@cdac.in', '05-Mar','Male', 'LCG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('219001','Dr (Ms) Padmaja Joshi','padmaja@cdac.in', '23-Feb','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('220401','Mr Ranjit P L','ranjitpl@cdac.in', '21-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('220501','Mr Rajeev Srivastava','rajeevs@cdac.in', '20-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('220701','Ms Ruta Khanvilkar','ruta@cdac.in', '09-Feb','Female', 'HRD');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('221501','Mr Sagun Baijal','sagun@cdac.in', '15-Oct','Male', 'OSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('224001','Mr Vijay Jain','vijayj@cdac.in', '13-Jan','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271138','Mr Peeyush Chomal','peeyush@cdac.in', '05-Oct','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271218','Mr P S Gandhi','psgandhi@cdac.in', '01-Jun','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271486','Ms Mercy Sobhan','mercy@cdac.in', '07-Mar','Female', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271544','Ms Rekha Nair','rekhap@cdac.in', '15-Sep','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271602','Ms Kavita Yadav','kavita@cdac.in', '14-Aug','Female', 'CNIE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271692','Ms Swapna Ballal','swapnab@cdac.in', '28-Sep','Female', 'HRD');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271693','Ms Shreya Bokare','shreya@cdac.in', '28-Apr','Female', 'CNIE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271842','Ms Akanksha Joshi','akanksha@cdac.in', '19-Mar','Female', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271892','Mr Tushar Koli','tushar@cdac.in', '17-Mar','Male', 'ACCOUNTS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271953','Mr Saurabh','saurabh@cdac.in', '23-Jun','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('272696','Ms Gayatri Antani','gayatri@cdac.in', '09-May','Female', 'ACCOUNTS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341270','Ms Naina Sonawani','nainas@cdac.in', '03-May','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341557','Mr Sathish Kumar Arumugasamy','asathish@cdac.in', '11-Jul','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341573','Mr Samadhan Rajaram Manore','samadhanm@cdac.in', '22-Jan','Male', 'OSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341625','Mr Arun G','garun@cdac.in', '20-May','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341658','Mr Sampathkumar Mende','sampath@cdac.in', '10-Jan','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341701','Mr Rakesh T','rakesht@cdac.in', '09-Mar','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342564','Mr Priyam Khare','priyamk@cdac.in', '31-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342572','Mr Saidarshan Ramesh Bhagat','saidarshan@cdac.in', '12-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344473','Mr Arvind Kumar','kumararvind@cdac.in', '29-Sep','Male', 'ITSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344554','Mr Chandra Sekhar Behera','chandrab@cdac.in', '24-Jun','Male', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344556','Mr Bade Sachin Narayan','bsachin@cdac.in', '10-Jan','Male', 'ITSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210103','Mr Anupam Saxena','anupam@cdac.in', '10-Aug','Male', 'CNIE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210301','Mr Ashok Bhosale','bashok@cdac.in', '13-Jul','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210602','Mr Chetan Ahirrao','chetan@cdac.in', '08-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('212301','Mr Bira Chandra Singh','bira@cdac.in', '01-Jun','Male', 'LCG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('216601','Mr Manoj Kumar Singh','smanoj@cdac.in', '04-Oct','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('218201','Mr Prakash Pimpale','prakash@cdac.in', '13-Dec','Male', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('221301','Mr Shashi Bhushan Prabhakar','shashi@cdac.in', '05-Jan','Male', 'CNIE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('222401','Ms Shilpa Oswal','soswal@cdac.in', '17-Nov','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('223201','Mr Uttam Kumawat','uttamkumawat@cdac.in', '21-Sep','Male', 'CNIE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('223401','Ms Veena Tyagi','vtyagi@cdac.in', '11-Jul','Female', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271225','Mr G M Dhumal','gmdhumal@cdac.in', '01-Jun','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271285','Ms Rachna Gupta','rachna@cdac.in', '10-Jul','Female', 'CANTEEN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271573','Mr Khetru More','khetrum@cdac.in', '22-Oct','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271632','Ms Rekha Sivasankaran','rekhas@cdac.in', '05-Apr','Female', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271633','Mr Reniguntla Sambaiah','reniguntla@cdac.in', '10-Feb','Male', 'OSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('272102','Mr Ramakant Gajanan Yeware','ramakant@cdac.in', '07-Nov','Male', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('340905','Mr Shiv Nath Kumar','shivnath@cdac.in', '04-Jan','Male', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210202','Mr Amar Sarkar','amars@cdac.in', '03-Apr','Male', 'CANTEEN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210204','Ms Seema Sapkal','seemas@cdac.in', '24-Aug','Female', 'ACCOUNTS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('210805','Mr B Mariappa','bmariappa@cdac.in', '18-Apr','Male', 'CANTEEN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('211801','Ms Anamika Singh','anamika@cdac.in', '09-Mar','Female', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('212201','Mr B C L Narasaiah','narasaiah@cdac.in', '28-May','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('213101','Mr Chandrakant Kate','chandrakantk@cdac.in', '26-May','Male', 'ITSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('213401','Ms Harshadaa  Shroff','dolly@cdac.in', '22-Apr','Female', 'ACCOUNTS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('213601','Ms Dhanashri Vaibhav Dalvi','dhanashri@cdac.in', '31-Dec','Female', 'ACCOUNTS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('214101','Ms Geeta Nair','geetan@cdac.in', '23-May','Female', 'ED Office');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('215101','Ms Jean Jojo','jean@cdac.in', '03-Nov','Female', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('215501','Mr Kunal Hatkar','kunalh@cdac.in', '09-Aug','Male', 'ACCOUNTS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('216401','Mr Laxman Jha','laxmanj@cdac.in', '03-May','Male', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('217401','Mr Mahesh Gujar','maheshg@cdac.in', '15-Mar','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('219201','Mr Prashant Dev','dprashant@cdac.in', '04-Nov','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('219501','Ms Rupali Shripad Todkar','rupali@cdac.in', '30-Aug','Female', 'Library');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('219901','Mr Ramchandra Gaikwad','ramchandrag@cdac.in', '01-May','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('221201','Mr Shrimant More','shrimantm@cdac.in', '01-May','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('221601','Mr Shashikant Kadam','kshashikant@cdac.in', '08-Apr','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('222101','Ms Suman Ninoriya','nsuman@cdac.in', '26-Oct','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('222301','Mr Santosh Kute','santoshkute@cdac.in', '01-Jun','Male', 'TRANSPORT');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('223501','Mr Vishwanath Kalsekar','vishwanathk@cdac.in', '10-Nov','Male', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('224101','Mr Varunkrishnan T K','varuntk@cdac.in', '11-Mar','Male', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271116','Ms Sweta Suhasaria','swetas@cdac.in', '08-Mar','Female', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('271141','Ms Anuradha Santosh','anuradhas@cdac.in', '23-Sep','Female', 'ACCOUNTS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341018','Mr Nikhil Singh Rajput','nikhilr@cdac.in', '12-Oct','Male', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341051','Ms Jayati Dwivedi','jayatid@cdac.in', '11-May','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341054','Mr Sudheer Kumar Kotha','sudheerk@cdac.in', '25-Mar','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341298','Ms Meghana S.Jagtap','jmeghana@cdac.in', '24-Jan','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341300','Mr Vaibhav Singh','vaibhavs@cdac.in', '01-Apr','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341301','Mr Vishal Dewarde','vishald@cdac.in', '13-Jun','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341305','Mr Mukund Kakde','mukundk@cdac.in', '27-Sep','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341309','Mr Madhur Ingale','imadhur@cdac.in', '30-May','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341311','Mr Nikhil S. Chinchole','nikhilc@cdac.in', '17-Nov','Male', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341464','Ms Priyanka Priyank Anbhavne','priyankam@cdac.in', '29-Apr','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341558','Mr Ahmad Hassan','ahmad@cdac.in', '10-Jul','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341580','Mr Abhishek Singh','abhisheksingh@cdac.in', '23-Aug','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341740','Mr Sagar Chandrakant Jadhav','jsagar@cdac.in', '09-Nov','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('341745','Ms Manali Badrike','manali@cdac.in', '29-May','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342013','Mr Shashank Patel','shashank@cdac.in', '26-Feb','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342063','Mr Tushar Shivlal Chavan','tusharc@cdac.in', '29-Sep','Male', 'LCG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342073','Mr Amitesh Banerjee','amiteshb@cdac.in', '16-Dec','Male', 'LCG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342077','Mr Mohinish Uzzwal','mohinish@cdac.in', '17-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342189','Dr Kavi Raju C','kavirajuc@cdac.in', '20-Feb','Male', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342228','Mr Amol Vishwanath Bole','amolb@cdac.in', '15-Dec','Male', 'LCG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342276','Mr Patil  Atul Ganesh','atulp@cdac.in', '25-Nov','Male', 'LCG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342311','Ms Jayshri Ashokrao Kharule','jayshrik@cdac.in', '26-Jan','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342351','Mr Aditya Sawant','adityas@cdac.in', '04-Apr','Male', 'CNIE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342352','Ms Bhavika Ninawe','bhavikan@cdac.in', '22-Oct','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342357','Mr Sandesh Mandhane','msandesh@cdac.in', '30-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342366','Mr Vinay Vijay Jadhav','jvinay@cdac.in', '07-Feb','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342367','Ms Vaishali Katkar','kvaishali@cdac.in', '15-Oct','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342404','Mr Abhijit Vidhate','abhijitv@cdac.in', '11-Aug','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342563','Ms Meghna Gupta','meghnag@cdac.in', '28-Dec','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342833','Mr Gajanan Shivaji Lobhe','gajanan@cdac.in', '30-Jun','Male', 'ITSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342853','Mr Sohan Suresh More','sohan@cdac.in', '09-Oct','Male', 'EDU TRN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342854','Mr Abhijit Bapurao Wagh','abhijit@cdac.in', '20-Jan','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342856','Mr Amit Kumar Upadhyay','amitu@cdac.in', '02-Jan','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('342930','Mr Tejas Ambadas Damale','tejas@cdac.in', '30-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343009','Mr Akshay Patil','akshaypatil@cdac.in', '15-May','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343029','Mr Mandar Pradeep Wadkar','mandarwadkar@cdac.in', '30-Jul','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343033','Ms Manasi Tanaji Khot','manasi@cdac.in', '10-Jan','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343036','Ms Sayali Abhijeet Chaudhari','sayali@cdac.in', '03-Apr','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343059','Ms Aishwarya Kale','aishwaryak@cadc.in', '02-Nov','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343071','Mr Rohan Nadkarni','nrohan@cdac.in', '03-Apr','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343199','Mr Ashish','hashish@cdac.in', '14-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343267','Mr Meerjada Altamas','meerjada@cdac.in', '12-Sep','Male', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343335','Mr Vijayendra Sunil Thosar','vijayendrat@cdac.in', '12-Oct','Male', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343336','Mr Vikas Dukare','dvikas@cdac.in', '06-Oct','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343406','Ms Sameeksha Katle','sameeksha@cdac.in', '20-Aug','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343407','Mr Pratik Sonawane','spratik@cdac.in', '26-Dec','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343433','Mr Pratik  B Patil','pratikpatil@cdac.in', '10-Jun','Male', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343509','Mr Ayan Datta','ayan@cdac.in', '07-Dec','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343511','Mr Amol Sarjerao Gawade','amolg@cdac.in', '09-Dec','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343527','Mr Vinay Hinukale','vinayh@cdac.in', '07-Mar','Male', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343528','Mr Akhilesh Kashikar','akhileshk@cdac.in', '28-Nov','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343529','Ms Nupur Paralkar','nupur_11@cdac.in', '11-Nov','Female', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343534','Ms Abhilasha Sharma','abhilashas@cdac.in', '29-May','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343536','Mr Nikhil Pawar','pnikhil@cdac.in', '18-Sep','Male', 'ITSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343564','Ms Shraddha Pawar','shraddhap@cdac.in', '08-Jan','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343566','Mr Nikhil Sonani','nikhils@cdac.in', '14-Dec','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343567','Ms Asawari Shinde','asawari@cdac.in', '08-Dec','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343568','Ms Shweta Pal','shwetapal@cdac.in', '02-May','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343633','Mr Arpit Bhatiya','arpit@cdac.in', '03-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343654','Mr Kunal Anil Utage','kunalu@cdac.in', '16-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343828','Ms Pratiksha Katale','pratikshak@cdac.in', '07-Jan','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343829','Mr Omkar Rajendra Karande','omkarrk@cdac.in', '06-Mar','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343831','Mr Prashik Ashok Ghutke','prashik@cdac.in', '23-Jan','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343836','Mr Kaustubh Dhananjay Zagade','kaustubhz@cdac.in', '30-Nov','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343839','Ms Nisha Shreedhar Dasame','dnisha@cdac.in', '28-Jan','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343840','Ms Shivani Verma','shivaniv@cdac.in', '28-Jun','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343842','Mr Shubham Rai','shubhamr@cdac.in', '01-Jan','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343944','Ms Nikita Gupta','gnikita@cdac.in', '23-Dec','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343949','Mr Kiran Ugalmugale','ukiran@cdac.in', '15-Feb','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343950','Mr Rohan Baliram Rakunde','rohanr@cdac.in', '29-Sep','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343954','Ms Vrushali Mahendra Chaudhari','vrushalic@cdac.in', '14-Oct','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343966','Mr Aakash Narayane','aakashn@cdac.in', '19-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343967','Mr Faizanur Rab','faizanur@cdac.in', '22-Jun','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343968','Ms Mokshada Pagare','mokshada@cdac.in', '01-Apr','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('343970','Mr Shashikant Khetmalis','shashi7507@cdac.in', '22-May','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344011','Mr Surendra Singh','surendras@cdac.in', '12-May','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344035','Ms Pragya Rani','pragya@cdac.in', '15-Aug','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344040','Ms Ramola Amit Bhowmik','ramola@cdac.in', '09-Jun','Female', 'ADMIN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344055','Mr Pravin Bhaskar Ramteke','pravinr@cdac.in', '11-Sep','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344107','Ms Shubhangi Suresh Sawant','shubhangis@cdac.in', '15-Jun','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344108','Ms Trupti Keshav Badhekar','truptib@cdac.in', '07-Dec','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344110','Mr Thamotharan Mani','thamom@cdac.in', '28-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344111','Ms Rutuja Deshpande','rutujad@cdac.in', '06-Nov','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344112','Ms Shilpi Priya Sen','shilpisen@cdac.in', '19-Apr','Female', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344113','Ms Supriya Jantre','supriyaj@cdac.in', '21-Apr','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344114','Ms Krushangi Patel','krushangi@cdac.in', '20-May','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344123','Ms Shefali Chapre','shefali@cdac.in', '11-Jan','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344130','Ms Asmita Suresh Babar','asmita@cdac.in', '15-Sep','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344149','Mr Ganesh Mahadeo Kharat','kganesh@cdac.in', '15-Apr','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344150','Mr Piyush Bhupendra Soney','piyushs@cdac.in', '04-Sep','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344152','Mr Preetam Bhosle','preetam@cdac.in', '10-Aug','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344154','Mr Omkar Ramakant Yeware','omkary@cdac.in', '17-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344155','Ms Sanvi Vikas Patil','sanvi@cdac.in', '15-Jan','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344162','Mr Rupesh Rajmal Patil','rupesh@cdac.in', '01-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344166','Ms Swati Gupta','swatigupta@cdac.in', '01-Jul','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344168','Mr Dipesh Chaudhari','dipeshc@cdac.in', '16-Jan','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344169','Ms Aishwarya Kapileshwar','kaishwarya@cdac.in', '27-Mar','Female', 'COURSE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344170','Ms Ashwini Jadhav','ashwinij@cdac.in', '25-Sep','Female', 'COURSE');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344171','Ms Shivangi Dubey','shivangid@cdac.in', '21-Nov','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344173','Mr Udit Kodgir','udit@cdac.in', '14-Mar','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344174','Mr Manoj Yadav','manojy@cdac.in', '27-Nov','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344175','Ms Sanjyot Sawant','sanjyot@cdac.in', '02-Dec','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344176','Ms Shweta Arun Karde','kshweta@cdac.in', '12-May','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344177','Mr Saurabh Mishra','msaurabh@cdac.in', '11-Jul','Male', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344178','Ms Priyanka Dudhat','priyanka107@cdac.in', '10-Aug','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344179','Ms Varsha Gawari','varshag@cdac.in', '17-May','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344180','Mr Mayank Rathore','rmayank@cdac.in', '12-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344181','Ms Priyanka Soni','psoni@cdac.in', '29-Apr','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344182','Mr Shubham Kulkarni','shubhamkulkarni@cdac.in', '10-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344183','Mr Saurabh Shahane','ssaurabh@cdac.in', '16-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344184','Ms Sarika Sonawane','sarika@cdac.in', '13-Aug','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344185','Mr Ganesh Kulkarni','ganeshkulkarni@cdac.in', '23-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344186','Mr Wali Hasan','wali@cdac.in', '13-Jul','Male', 'ITSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344187','Mr Tejaswini Patil','tejaswini@cdac.in', '25-Dec','Female', 'ITSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344188','Mr Aditya Bhavi','adityabhavi@cdac.in', '11-Jun','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344190','Mr Anil Kumar Chaurasiya','anilc@cdac.in', '10-Jul','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344211','Ms Puja Arkal','apuja@cdac.in', '14-Feb','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344212','Ms Ankita Gautam','ankitag@cdac.in', '12-Mar','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344261','Mr Sandesh Jadhav','sandesh@cdac.in', '11-Oct','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344306','Mr Amit Rathor','amitr@cdac.in', '18-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344308','Mr Swapnil Patre','swapnilp@cdac.in', '04-Apr','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344315','Ms Neha Narkhede','nehan@cdac.in', '05-Jun','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344317','Ms Shweta Mahajan','shwetam@cdac.in', '25-Sep','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344346','Ms Bhagyashree Joshi','bhagyas@cdac.in', '27-Apr','Female', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344347','Ms Tushar Digambar Rane','tushard@cdac.in', '05-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344348','Mr Deepanjan Joth','deepanjan@cdac.in', '18-Apr','Male', 'BIOMETRICS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344349','Mr Abhishek Deshpande','abhid@cdac.in', '19-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344350','Ms Sayali Rane','rsayali@cdac.in', '13-Jul','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344351','Mr Chetan Sunil Sonawane','chetanss@cdac.in', '22-Nov','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344352','Mr Rohit Vikas Patil','rpatil@cdac.in', '23-Mar','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344353','Mr Nirmal Dilip Jain','nirmald@cdac.in', '06-Jan','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344354','Mr Akash Fuldeore','akashf@cdac.in', '14-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344355','Mr Raj Bhosle','braj@cdac.in', '11-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344356','Mr Hanmant Annarao Bawage','hanmant@cdac.in', '27-Mar','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344357','Mr Prathmesh Ashok Kesare','prathmesh@cdac.in', '18-Sep','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344358','Mr Anurag Shrivastava','anuragsh@cdac.in', '24-Jun','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344359','Mr Onkar Arun Patil','onkar@cdac.in', '28-Dec','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344360','Mr Adinath Sanjay Raut','adinath@cdac.in', '20-Nov','Male', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344361','Mr Neil Shah','neilshah@cdac.in', '28-Mar','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344362','Mr Prasanna Borate','bprasanna@cdac.in', '09-Apr','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344363','Mr Sumit Ade','asumit@cdac.in', '08-Jun','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344364','Ms Mokshika Joshi','mokshika@cdac.in', '20-Dec','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344365','Ms Bhagyashri Sanjay Deore','bhaghyashri@cdac.in', '12-Aug','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344366','Mr Anagha Borkar','anagha@cdac.in', '30-Jun','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344367','Ms Rasika Shendage','rasika@cdac.in', '05-Aug','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344368','Mr Dnyandeep Yadav','dnyandeep@cdac.in', '11-Nov','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344369','Mr Shubham Patel','skalpesh@cdac.in', '05-Apr','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344370','Mr Yogesh Amle','yamle@cdac.in', '07-May','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344371','Mr Suyash Opalkar','ssuyash@cdac.in', '24-Dec','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344372','Ms Kalyani Thakare','kalyani@cdac.in', '15-Nov','Female', 'KBCS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344373','Mr Arjun Trivedi','arjunt@cdac.in', '25-May','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344374','Ms Madhuri Madhukar Patil','pmadhuri@cdac.in', '24-Apr','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344385','Ms Manorama Pawar','manoramap@cdac.in', '12-May','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344387','Mr Prathamesh Patil','prathamesh@cdac.in', '07-Mar','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344389','Ms Komal Wagdare','wkomal@cdac.in', '10-May','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344390','Mr Kaushal Balte','kaushalb@cdac.in', '10-Aug','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344442','Ms Nirmala Devmane','knirmala@cdac.in', '02-May','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344443','Ms Dhanashri Vijay Bagul','dhanashrib@cdac.in', '08-Nov','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344446','Mr Ramakrishna Kulkarni','krama@cdac.in', '22-Feb','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344470','Mr Ganesh Ramchandra Pawar','ganeshp@cdac.in', '07-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344471','Mr Ashish Ashok Shelar','ashelar@cdac.in', '29-May','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344472','Ms Swapnali Umaji Chavan','swapnali@cdac.in', '01-Sep','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344476','Mr Himanshu Katkar','himanshuk@cdac.in', '24-Jul','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344478','Ms Asmita Vijay Patil','asmitap@cdac.in', '07-Feb','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344479','Ms Shweta Bhere','shweta@cdac.in', '15-Jul','Female', 'EDU TRN');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344480','Mr Rushikesh Joshi','rushikeshj@cdac.in', '21-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344481','Mr Prateek Singh','prateek@cdac.in', '24-Dec','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344482','Mr Rushikesh Pradip Ghantewar','rushikeshg@cdac.in', '17-Jul','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344483','Mr Ruchit Ramugade','ruchit@cdac.in', '23-May','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344484','Ms Roshani Ashok Deoghare','roshanid@cdac.in', '13-Sep','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344486','Mr Amit  Raosaheb Walunj','amitw@cdac.in', '08-Jan','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344487','Ms Pratiksha  Gopal Khade','pratiksha@cdac.in', '14-Apr','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344488','Ms Muskan Chetan Garle','muskan@cdac.in', '10-May','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344489','Ms Manasi Sunil Sukate','manasis@cdac.in', '24-Mar','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344490','Ms Komal Kudave','kkomal@cdac.in', '02-Nov','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344491','Ms Ashita Markale','ashita@cdac.in', '19-Nov','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344492','Mr Aniket Krushnat Gaikwad','aniket@cdac.in', '27-Jun','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344493','Mr Vaibhav Jadhav','vaibhavj@cdac.in', '05-Dec','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344494','Mr Aamir Nabeel Khan','aamirk@cdac.in', '04-Dec','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344495','Mr Shubham Krishnakant Choube','cshubham@cdac.in', '14-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344502','Ms Pooja Sanjayrao Patil','poojapatil@cdac.in', '07-Jun','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344503','Ms Abhaya Haribhau Pathak','abhaya@cdac.in', '28-Sep','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344504','Mr Tejas Chandrashekhar Jadhav','tejasj@cdac.in', '23-Nov','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344505','Mr Saurabh Rajkumar Asalkar','saurabha@cdac.in', '23-Sep','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344506','Ms Shruti Jhariya','SHRUTI JHARIYA <shrutij@cdac.in', '10-Sep','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344507','Ms Gandhali Sandeep Temkar','gandhali@cdac.in', '26-Feb','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344508','Mr Kalpesh Shankar Sonawane','kalpeshs@cdac.in', '01-Apr','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344509','Mr Ritesh Manojkumar Jain','riteshj@cdac.in', '28-Apr','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344510','Mr Shubham Awasarkar','shubhamra@cdac.in', '24-Feb','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344511','Ms Dhanashree Tukaram Sutar','dhanashrees@cdac.in', '16-Jan','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344512','Ms Pooja Dayaram Patil','pdpatil@cdac.in', '24-Aug','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344513','Mr Vikash Batham','vikashb@cdac.in', '25-Aug','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344514','Ms Tejashri Anil Kundalwal','tejashrik@cdac.in', '22-Dec','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344516','Mr Swaraj Sunil Adhav','swaraj@cdac.in', '17-Jan','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344517','Mr Vikas Vishwakarma','vvikas@cdac.in', '03-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344518','Mr Somnath Bhagwat Satpute','somnaths@cdac.in', '17-Mar','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344519','Ms Mrunali Vijay Kapse','mrunalik@cdac.in', '04-Feb','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344520','Ms Aboli Sanjay Shinde','abolis@cdac.in', '05-Mar','Female', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344521','Mr Magan Singh Yadav','magan@cdac.in', '01-Feb','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344522','Mr Saurabh Bhedodkar','sbhedodkar@cdac.in', '24-Apr','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344523','Mr Auodumbar Vithalrao Mande','auodumbar@cdac.in', '16-Jun','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344524','Mr Umakant Sudhakar Bedse','umakant@cdac.in', '21-Sep','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344527','Mr Hardik Sharma','hardik@cdac.in', '02-Mar','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344536','Mr Saurabh Ashok Sarda','saurabhsarda@cdac.in', '26-Sep','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344537','Mr Rahul Motilal Yede','rahulyede@cdac.in', '26-Jan','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344538','Mr Kamal Kant','kamalk@cdac.in', '10-Mar','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344539','Ms Aishwarya Avinash Kamble','aishwarya@cdac.in', '23-Nov','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344544','Mr Akshay Sanjay Chavan','akshayc@cdac.in', '22-Nov','Male', 'ITSS');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344545','Ms Neha Saini','nehasaini@cdac.in', '07-Aug','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344551','Mr Himalaya  Dubey','himalaya@cdac.in', '31-Oct','Male', 'SENG');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344612','Mr Abhishek Pal','abhishekpal@cdac.in', '21-Mar','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344641','Mr Khan Shadab Naoshad','khans@cdac.in', '03-Mar','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344651','Mr Muhammad Kasim','muhammadk@cdac.in', '20-Jun','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344670','Ms Seema Shirose','seema@cdac.in', '06-Sep','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344684','Ms Shalaka Parab','Shalaka@cdac.in', '17-Jun','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344685','Mr Debmalya Paul','debp@cdac.in', '15-Sep','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344688','Mr Ashish Velaji Waghela','ashishw@cdac.in', '31-Jan','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344692','Mr Robin Johri','robinj@cdac.in', '12-Mar','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344724','Ms Kewal Sanjay Jadhav','kewal@cdac.in', '12-Dec','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344736','Ms Ira Ambole','iraambole@cdac.in', '12-Apr','Female', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344737','Mr Saurav Kumar','sauravkumar@cdac.in', '07-Aug','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344751','Mr Sahani Samant Gama','samant@cdac.in', '30-Oct','Male', 'ETU');
INSERT into birthday( emp_id, employee_name, email, data_of_birth, gender, groupid ) values  ('344752','Mr Shreeshail Vikram Sarate','shreeshail@cdac.in', '20-Oct','Male', 'ETU');
